### ISSUE TITLE
Handle unauthorized gracefully in UI

### ISSUE THREAD

**Issue by mikkelhegn** [mikkelhegn/redirect#11]

**Comment by mikkelhegn** [comment]
E.g., 

`https://asease:asfasffas@my-redirect.fermyon.app/admin/`

```
Script.js:9 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /api
    at get_data (script.js:9:2)
    at init (script.js:4:2)
    at (index):99:3
```
